[package]
name = "demview"
version = "0.1.0"
edition = "2021"

[dependencies]
kiss3d = "0.35.0"
env_logger = "0.10.0"
log = "0.4.17"
clap = { version = "4.1.4", features = ["derive"] }
anyhow = "1.0.69"
ghosting = { path = "../ghosting" }
